steps:
  - name: gcr.io/cloud-builders/git
    id: fetch-nested-submodules
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail

        # helper: klay-music/klay-audiotools  -> CSR URL
        csr() {
          local repo_path="$1"
          echo "https://source.developers.google.com/p/klay-home/r/github_${repo_path//\//_}"
        }

        ################################################################
        # 1) First-level sub-modules -----------------------------------
        ################################################################
        echo "▶ rewriting 1st-level modules"
        git config -f .git/config submodule.submodules/klay-data.url   "$(csr klay-music/klay-data)"
        git config -f .gitmodules submodule.submodules/klay-data.url "$(csr klay-music/klay-data)"
        git config -f .git/config submodule.submodules/klay-codecs.url "$(csr klay-music/klay-codecs)"
        git config -f .gitmodules submodule.submodules/klay-codecs.url "$(csr klay-music/klay-codecs)"

        git submodule sync          # flush config cache
        git submodule update --init klay_beam/submodules/klay-data \
                                        klay_beam/submodules/klay-codecs

        ################################################################
        # 2) Second-level: inside klay-data ----------------------------
        ################################################################
        echo "▶ rewriting 2nd-level modules (klay-data)"
        git config -f .git/modules/klay_beam/submodules/klay-data/config \
          submodule.submodules/klay-audiotools.url "$(csr klay-music/klay-audiotools)"
        git config -f klay_beam/submodules/klay-data/.gitmodules \
          submodule.submodules/klay-audiotools.url "$(csr klay-music/klay-audiotools)"
        git submodule update --init klay_beam/submodules/klay-data/submodules/klay-audiotools

        ################################################################
        # 3) Second-level: inside klay-codecs --------------------------
        ################################################################
        echo "▶ rewriting 2nd-level modules (klay-codecs)"
        git config -f .git/modules/klay_beam/submodules/klay-codecs/config \
          submodule.submodules/klay-nac.url "$(csr klay-music/klay-nac)"
        git config -f klay_beam/submodules/klay-codecs/.gitmodules \
          submodule.submodules/klay-nac.url "$(csr klay-music/klay-nac)"

        git submodule update --init klay_beam/submodules/klay-codecs/submodules/klay-nac

        ################################################################
        # 4) Third-level: inside klay-nac ------------------------------
        ################################################################
        echo "▶ rewriting 3rd-level modules (klay-nac)"
        git config -f .git/modules/klay_beam/submodules/klay-codecs/modules/submodules/klay-nac/config \
          submodule.submodules/klay-config.url "$(csr klay-music/klay-config)"
        git config -f klay_beam/submodules/klay-codecs/submodules/klay-nac/.gitmodules \
          submodule.submodules/klay-config.url "$(csr klay-music/klay-config)"

        git submodule update --init klay_beam/submodules/klay-codecs/submodules/klay-nac/submodules/klay-config

        echo "✅ all nested sub-modules fetched from CSR"
  - name: 'gcr.io/cloud-builders/docker'
    id: build-image
    args: ['build', '-f', 'jobs/job_klaynac/Dockerfile', '-t', '${_IMG}', '.']

  # Formatting and testing goes here when ready

  - name: 'gcr.io/cloud-builders/docker'
    id: publish-image
    args: ['push', '${_IMG}']
    waitFor:
      - build-image

  - name: 'gcr.io/cloud-builders/docker'
    id: tag-image
    args: ['tag', '${_IMG}:latest', '${_IMG}:${TAG_NAME}']

timeout: 3600s  # 1 hour

images: ['${_IMG}']

options:
  dynamic_substitutions: true
  substitution_option: 'ALLOW_LOOSE'
  machineType: 'E2_HIGHCPU_8'
  logging: 'CLOUD_LOGGING_ONLY'

substitutions:
  _REPO: 'us-docker.pkg.dev/klay-home/klay-docker'
  _IMG: '${_REPO}/klay-beam-klaynac'
