steps:
  - name: gcr.io/cloud-builders/git
    id: git-creds
    secretEnv: ['GH_PAT']
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail

        echo "🔐 Setting up GitHub PAT for all HTTPS fetches"
        # (A) Tell Git to inject the token whenever it sees https://github.com/
        git config --global url."https://${GH_PAT}:x-oauth-basic@github.com/".insteadOf https://github.com/

        # (B) For SSH-style URLs, convert them on the fly
        git config --global url."https://${GH_PAT}:x-oauth-basic@github.com/".insteadOf git@github.com:
        git config --global url."https://${GH_PAT}:x-oauth-basic@github.com/".insteadOf ssh://git@github.com/

        # (Optional) silence "terminal prompts disabled" warnings
        git config --global --add url."https://${GH_PAT}:x-oauth-basic@github.com/".pushInsteadOf no_push

        echo "✅ GitHub credential helper configured"

  - name: gcr.io/cloud-builders/git
    id: fetch-submodules
    entrypoint: bash
    args: ['-c', 'git submodule update --init --recursive']

  - name: 'gcr.io/cloud-builders/docker'
    id: build-image
    args: ['build', '-f', 'jobs/job_klaynac/Dockerfile', '-t', '${_IMG}', '.']

  # Formatting and testing goes here when ready

  - name: 'gcr.io/cloud-builders/docker'
    id: publish-image
    args: ['push', '${_IMG}']
    waitFor:
      - build-image

  - name: 'gcr.io/cloud-builders/docker'
    id: tag-image
    args: ['tag', '${_IMG}:latest', '${_IMG}:${TAG_NAME}']

timeout: 3600s  # 1 hour

images: ['${_IMG}']

options:
  dynamic_substitutions: true
  substitution_option: 'ALLOW_LOOSE'
  machineType: 'E2_HIGHCPU_8'
  logging: 'CLOUD_LOGGING_ONLY'

substitutions:
  _REPO: 'us-docker.pkg.dev/klay-home/klay-docker'
  _IMG: '${_REPO}/klay-beam-klaynac'


availableSecrets:
  secretManager:
    - versionName: projects/klay-home/secrets/github-pat/versions/latest
      env: 'GH_PAT'
