steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: build-image
    args: ['build', '-f', 'jobs/job_demucs/Dockerfile', '-t', '${_IMG}', '.']

  # Formatting and testing goes here when ready

  - name: 'gcr.io/cloud-builders/docker'
    id: publish-image
    args: ['push', '${_CONTROLLER_IMG}']
    waitFor:
      - build-image

timeout: 3600s  # 1 hour

images: ['${_IMG}']

options:
  dynamic_substitutions: true
  substitution_option: 'ALLOW_LOOSE'
  machineType: 'E2_HIGHCPU_8'
  logging: 'CLOUD_LOGGING_ONLY'

substitutions:
  _REPO: 'us-docker.pkg.dev/klay-home/klay-docker'
  _IMG: '${_REPO}/klay-beam-demucs'
