steps:
  - name: 'gcr.io/cloud-builders/git'
    id: fetch-submodules
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git init .
        git config -f .git/config submodule.submodules/klay-audiotools.url https://source.developers.google.com/p/klay-home/r/github_klay-music_klay-audiotools
        git config -f .gitmodules submodule.submodules/klay-audiotools.url https://source.developers.google.com/p/klay-home/r/github_klay-music_klay-audiotools
        git config -f .git/config submodule.submodules/klay-config.url https://source.developers.google.com/p/klay-home/r/github_klay-music_klay-config
        git config -f .gitmodules submodule.submodules/klay-config.url https://source.developers.google.com/p/klay-home/r/github_klay-music_klay-config
        git config -f .git/config submodule.submodules/klay-nac.url https://source.developers.google.com/p/klay-home/r/github_klay-music_klay-nac
        git config -f .gitmodules submodule.submodules/klay-nac.url https://source.developers.google.com/p/klay-home/r/github_klay-music_klay-nac
        git config -f .git/config submodule.submodules/klay-codecs.url https://source.developers.google.com/p/klay-home/r/github_klay-music_klay-codecs
        git config -f .gitmodules submodule.submodules/klay-codecs.url https://source.developers.google.com/p/klay-home/r/github_klay-music_klay-codecs
        git submodule update --init --recursive klay_beam/submodules/klay-codecs

  - name: 'gcr.io/cloud-builders/docker'
    id: build-image
    args: ['build', '-f', 'jobs/job_klaynac/Dockerfile', '-t', '${_IMG}', '.']

  # Formatting and testing goes here when ready

  - name: 'gcr.io/cloud-builders/docker'
    id: publish-image
    args: ['push', '${_IMG}']
    waitFor:
      - build-image

  - name: 'gcr.io/cloud-builders/docker'
    id: tag-image
    args: ['tag', '${_IMG}:latest', '${_IMG}:${TAG_NAME}']

timeout: 3600s  # 1 hour

images: ['${_IMG}']

options:
  dynamic_substitutions: true
  substitution_option: 'ALLOW_LOOSE'
  machineType: 'E2_HIGHCPU_8'
  logging: 'CLOUD_LOGGING_ONLY'

substitutions:
  _REPO: 'us-docker.pkg.dev/klay-home/klay-docker'
  _IMG: '${_REPO}/klay-beam-klaynac'
