name: demucs-dev

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - numpy=1.23
  - ffmpeg>=4.2,<5
  - pytorch::pytorch>=2
  - pytorch::torchaudio>=2
  - pip

  - pip:
    - -e '..[code-style, tests, type-check]'
