name: clap-dev

# This describes the development and launch environment.
#
# IMPORTANT: If you change the dependencies here, you should also make sure the
# default Docker image (which is likely pined in the bin/run_job_<name>.py
# script) also reflects your changes.

channels:
  - defaults
  - conda-forge

dependencies:
  - pip
  - python=3.9
  - numpy=1.23
  - ffmpeg>=4.2,<5
  # libiconv and xorg-libxau are required for ffmpeg
  - conda-forge::libiconv=1.17
  - conda-forge::xorg-libxau=1.0
  # libsndfile 1.2.0 is required for the soundfile pip package
  - conda-forge::libsndfile>=1.2.0
  # Pin pytorch to guarantee the same version in Docker/Dataflow runtime
  - pytorch::pytorch=2.0
  - pytorch::torchaudio=2.0
  - pytorch::torchvision=0.15

  - pip:
    - -e '..[code-style, tests, type-check]'