name: demucs

channels:
  - defaults
  - pytorch
  - conda-forge

dependencies:
  - python=3.9
  - ffmpeg>=4.2,<5
  # demucs uses pytorch 1.8.1 (https://github.com/facebookresearch/demucs/blob/main/environment-cuda.yml)
  # klaypy uses 1.12 (https://github.com/klay-music/klaypy/blob/main/environment/linux-64.yml)
  # Technically >=1.9 should be valid.
  - pytorch::pytorch>=1.12
  - torchaudio>=0.8
  - tqdm>=4.36
  - pip
  # demucs is listed as a dependency in the job_demucs package's pyproject.toml.
  # However, it is specified as a git dependency, so the the conda environment
  # needs to have git installed locally
  - git