name: adt

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - ffmpeg>=4.2,<5
  - pip

  - pip:
    - -e '../klay_beam[code-style, tests, type-check]'
    - -e '../job_adt[code-style, tests, type-check]'
