name: job-klaynac

channels:
  - defaults

dependencies:
  - python=3.10
  - numpy=>1.23,<2
  - conda-forge::ffmpeg>=4.2,<5
  - pytorch::pytorch>=2
  - pytorch::torchaudio
  - pip

  - pip:
    - -e '../../../klay_beam/submodules/klay-codecs/submodules/klay-nac/submodules/klay-data/submodules/klay-audiotools'
    - -e '../../../klay_beam/submodules/klay-codecs/submodules/klay-nac[type-check, code-style, tests]'
    - -e '../../../klay_beam/submodules/klay-codecs/submodules/klay-nac/submodules/klay-config'
    - -e '../../../klay_beam/submodules/klay-codecs[code-style, tests, type-check]'
    - -e '..[code-style, tests, type-check]'
