name: on-pull-request

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  code_style:
    strategy:
      matrix:
        python: ['3.10']
        os: ['ubuntu-latest']
    name: code_style
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install '.[code-style]'
      - name: Run code-style
        run: |
          make code-style
  type_checking:
    strategy:
      matrix:
        python: ['3.10']
        os: ['ubuntu-latest']
    name: type_checking
    runs-on: ${{  matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update submodule
        run: |
          git submodule update --init
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U '.[type-check]'
      - name: Run type-check
        run: |
          make type-check
  run_tests:
    strategy:
      matrix:
        python: ['3.10']
        os: ['ubuntu-latest']
    name: run_tests
    runs-on: ${{ matrix.os }}
    needs: [type_checking, code_style]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update submodule
        run: |
          git submodule update --init
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: klay-data
          environment-file: environment.yml
          python-version: ${{ matrix.python }}
          auto-activate-base: false
          use-only-tar-bz2: true
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install ffmpeg
          pytest tests
