name: publish-docker-hub

on:
  push:
    branches:
      - 'publish-docker-hub'

jobs:
  docker:
    strategy:
      matrix:
        dockerHelperConfig:
          # These lines below refer to conda lock files in the
          # `klay-beam/environment` dir. If you want to add a new configuration,
          # it is not enough to just add a new line below. You must also ensure
          # that an appropriately named conda lock file exists with the with the
          # specified torch, torchvision, cuda versions.
          #
          # Note that the lines below may change the `BEAM_VERSION` without
          # adding a conda lock file. This is because the python `apache-beam`
          # package is installed Dockerfile.conda. Adding `BEAM_VERSION=2.50.0`
          # to one of the lines below will just override the default apache-beam
          # version specified in docker-env-helper.sh.
          #
          # Python 3.9
          - PY_VERSION=3.9;
          - PY_VERSION=3.9; TORCH_VERSION=2.0;
          - PY_VERSION=3.9; TORCH_VERSION=2.0; TORCHVISION_VERSION=0.15;
          # PYTHON 3.10
          - PY_VERSION=3.10;
          - PY_VERSION=3.10; TORCH_VERSION=2.5;
          - PY_VERSION=3.10; TORCH_VERSION=1.11; CUDA_VERSION=11.3;
          - PY_VERSION=3.10; TORCH_VERSION=2.1; CUDA_VERSION=12.1;
          - PY_VERSION=3.10; TORCH_VERSION=2.5; CUDA_VERSION=12.1;
          # PYTHON 3.11
          - PY_VERSION=3.11;
          - PY_VERSION=3.11; TORCH_VERSION=2.0;

    runs-on: ubuntu-latest-4core
    steps:
      - uses: shaunco/ssh-agent@git-repo-mapping
        with:
          ssh-private-key: |
            ${{ secrets.KLAY_DATA_ACCESS_TOKEN }}
            ${{ secrets.AGC_ACCESS_TOKEN }}
            ${{ secrets.KLAY_AUDIOTOOLS_ACCESS_TOKEN }}
            ${{ secrets.KLAY_CODECS_ACCESS_TOKEN }}
            ${{ secrets.KLAY_CONFIG_ACCESS_TOKEN }}
            ${{ secrets.KLAY_NAC_ACCESS_TOKEN }}
            ${{ secrets.KLAY_MTRPP_ACCESS_TOKEN }}
          repo-mappings: |
            github.com/klay-music/klay-data
            github.com/klay-music/agc
            github.com/klay-music/klay-audiotools
            github.com/klay-music/klay-codecs
            github.com/klay-music/klay-config
            github.com/klay-music/klay-nac
            github.com/klay-music/klay-mtrpp
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update submodule
        run: |
          git submodule update --init
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Environment Variables
        id: get_variables
        working-directory: ./klay_beam
        run: |
          ${{ matrix.dockerHelperConfig }}
          source ./docker-env-helper.sh
          echo "KLAY_BEAM_VERSION=${KLAY_BEAM_VERSION}" >> $GITHUB_OUTPUT
          echo "PY_VERSION=${PY_VERSION}"               >> $GITHUB_OUTPUT
          echo "BEAM_VERSION=${BEAM_VERSION}"           >> $GITHUB_OUTPUT
          echo "LOCAL_CONDA_LOCK=${LOCAL_CONDA_LOCK}"   >> $GITHUB_OUTPUT
          echo "DOCKER_TAG=${DOCKER_TAG}"               >> $GITHUB_OUTPUT
          echo "DOCKER_HUB_IMAGE=${DOCKER_HUB_IMAGE}"   >> $GITHUB_OUTPUT
          echo "DOCKER_GCP_IMAGE=${DOCKER_GCP_IMAGE}"   >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./klay_beam/Dockerfile.conda
          context: ./klay_beam/
          push: true
          tags: |
            ${{ steps.get_variables.outputs.DOCKER_HUB_IMAGE }}
          build-args: |
            PY_VERSION=${{ steps.get_variables.outputs.PY_VERSION }}
            BEAM_VERSION=${{ steps.get_variables.outputs.BEAM_VERSION }}
            LOCAL_CONDA_LOCK=${{ steps.get_variables.outputs.LOCAL_CONDA_LOCK }}
